### ISSUE TITLE
[6주차 리뷰] 인접리스트 구현 부분

### ISSUE THREAD

**Issue by ing03201** [algorithmSSU/yejiHong#2]
문제범위 까지의 vector를 정의하지말고 vector<vector<int>> 자료형을 바꾸면 좀 더 메모리 점유를 줄일수 있을거같아요.
visited 배열은 혹시 vector로 구현 안한 이유는 무엇인가요?

**Comment by yj120** [comment]
visited 배열은 그래프, 경로의 비용을 계산하는 자료구조와 동일하게 해서 방문을 체크하는 것이 더 직관적으로 이해하기 쉬워서 그랬던 것 같습니다. 

다른 문제에서 vector<int> arr[] 를 사용했던 것도 이해하기 쉬워서 그렇게 사용했고, 메모리 점유 문제는 고려하지 못했던 거 같습니다. 짚어주셔서 감사합니다.
